### ISSUE TITLE
android version?

### ISSUE THREAD

**Issue by ghost** [NathanWalker/nativescript-ezaudio#7]
Hi Nathan,

Will we ever see android version of this plugin in 2018? 
I would really appreciate that! 

Thanks in advance,

**Comment by NathanWalker** [comment]
Hi @jamesharvey2 the Cocoapod for iOS used here has been since rolled into [AudioKit](http://audiokit.io/). 

I highlight how to integrate the AudioKit version in this book:
https://www.packtpub.com/web-development/nativescript-angular-mobile-development
Which also includes integration of the Android side using this library:
https://github.com/Yalantis/Horizon

I will consider releasing a {N} plugin next year based off what was shown in the book but for now you can refer to that for all the details.

**Comment by ghost** [comment]
Thanks a lot! 
I would really appreciate that. .This audio plug-in is some of the best I've seen. I'm intrested in AudioKit as well but it's for iOS only. I'm into android for now. Is it possible to use AudioKit & Angular 5 on NativeScript for an android project? does it work fine? for instance, I wonder if audiokit running on android will provide native sound playback using android's sound engine...   Web Audio API can create synthesizer just like AudioKit but it's limited to HTML5 audio which is not stable on all android phones.

I want to buy your book as well. I'm coming from Angular 5 developer background. 
If you make your book into a tutorial video, I would appreciate that too! NativeScript seems to be getting more popularity. 
Thanks again and happy holidays.

**Comment by ghost** [comment]
Hi Nathan,

I found out AudioKit is the most powerful audio framework for mobile devices.. if possible please release audiokit as a plugin for NativeScript (android & iOS). 
It looks like AudioKit has every feature of Web Audio API and does provide native playback on android & iOS. I would appreciate if you make this happen in 2018!
